### ISSUE TITLE
Multi WaterMark Add

### ISSUE THREAD

**Issue by MehmetNuri** [binarystash/pdf-watermarker#16]
Hi, i want multi water mark one pdf file . How i make it? 

**Example**
- marker1:  demo1.png,  pozition: bottom left
- marker2: demo2.png, pozition : bottom right
- marker3: 'Text', pozition: bottom center

**Comment by robertclarkson** [comment]
Execute the watermarking code several times, each time using the output from the previous time

**Comment by MehmetNuri** [comment]
> 
> 
> Execute the watermarking code several times, each time using the output from the previous time

This does not fit the programming logic
