### ISSUE TITLE
WaterMark Image Hide Pdf Content

### ISSUE THREAD

**Issue by mkhalil** [binarystash/pdf-watermarker#3]
Hello,

When adding an image to PDF using this script I get the image over the original PDF and not under it as watermark

Can you help me please the given image under the original pdf text and not over it ?

Best regards,
khalil

**Comment by mkhalil** [comment]
Here is the code that I'm using

<?php

require_once('fpdf/fpdf.php');
require_once('fpdi/fpdi.php');
require_once('pdfwatermarker/pdfwatermark.php');
require_once('pdfwatermarker/pdfwatermarker.php');


class PDFWatermarkUtil {
	
	public static function addImageHeader($filePath) {
		if (defined('PATH_IMAGE_WATER_MARK')) {
			//Specify path to image
			$watermark = new PDFWatermark(PATH_IMAGE_WATER_MARK); 
		
			//Specify the path to the existing pdf, the path to the new pdf file, and the watermark object
			$watermarker = new PDFWatermarker($filePath, $filePath, $watermark); 
		
			//Set the position
			$watermarker->setWatermarkPosition('topleft');
		
			//Save the new PDF to its specified location
			$watermarker->watermarkPdf(); 
		}
	}
}

**Comment by mehditaly** [comment]
Hello,
I have exactly the same problem as described here 
The Watermark Image is over text in PDF 

How to set it as a background ?
Best regards

**Comment by binarystash** [comment]
Hi,

A feature to set the watermark as background was added. See the [project page](https://github.com/binarystash/pdf-watermarker#usage) for details.

Thanks!
