### ISSUE TITLE
Width A4

### ISSUE THREAD

**Issue by mehditaly** [binarystash/pdf-watermarker#4]
Hello,
when I export a PNG (with illustrator or Photoshop) with A4 dimensions and when I send an A4 PDF the background is smaller than PDF 

I set : topleft position 
Any help please 
Best regards

**Comment by binarystash** [comment]
Hi,

The PNG must have a 96 DPI resolution. On Photoshop CS5, this may changed via Image->Image Size->Resolution.

Thanks!

**Comment by mehditaly** [comment]
Thank you very much ;)
