### ISSUE TITLE
Add a new page to set the watermark there

### ISSUE THREAD

**Issue by TimmyToole** [binarystash/pdf-watermarker#5]
Hi,
I've been checking your library but i can't find the way to create a new page and force the watermark to be set there.

Those are the changes that i've made on you Watermarker class:

	public function addPage () {
		$this->_tempPdf->AddPage();
	}

	public function setMarkOnPage ($page = 1) {
		$this->watermarkPage = $page;
	}
	
	/**
	 * Loop through the pages while applying the watermark
	 *
	 * @return void
	 */
	private function _updatePDF() {
		$pageCtr = $this->_tempPdf->setSourceFile($this->_originalPdf);
		if (!empty($this->watermarkPage)) {
			$this->_watermarkPage($this->watermarkPage);
		} else {
			for($ctr = 1; $ctr <= $pageCtr; $ctr++){
				$this->_watermarkPage($ctr);
			}
		}
	}

The result is the existing PDF with a new page added (the first page) but with the watermark begin set on page 2.

	        $watermark = new PDFWatermark(PATH_IMAGE_WATER_MARK);
	        
	        //Set the position
	        $watermark->setPosition('center');
	        $watermark->setAsBackground(); 

	        //Specify the path to the existing pdf, the path to the new pdf file, and the watermark object
	        $watermarker = new PDFWatermarker($filePath, $tmpFilePath, $watermark);
	        
	        $watermarker->addPage();
	        $watermarker->setMarkOnPage(1); 

	        //Save the new PDF to its specified location
	        $watermarker->savePdf();

**Comment by binarystash** [comment]
Hi Timmy,

The PDFWatermarker class was modified to allow page ranges. You may now use the following to target specific pages.

```
$watermarker->setPageRange(1,1) //Watermark page 1
$watermarker->setPageRange(3,5) //Watermark pages 3-5
$watermarker->setPageRange(5) //Watermark pages 5 onwards
```

Thanks!
